# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZ9w51D4lTXsrSo7Wm4xmAMWIpxfmC9y
"""

from app import create_app

# Create application instance
app = create_app()

if __name__ == "__main__":
    app.run()

